{include file="library/header.lbi"}
<body>
<script src="js/jquery.modal.min.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="css/jquery.modal.css" type="text/css" media="screen" />

{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">商品交易明细</h5>
        <div class="pull-right">
            <a class="btn btn-primary" href="?act=trade_summary">交易汇总</a>
            <a class="btn btn-primary" href="?act=order_list">订单交易明细</a>
            <a class="btn btn-primary" href="?act=category_calendar">分类销售汇总</a>
            <a class="btn btn-primary" href="?act=sale_summary">畅销时间图表</a>
            <a class="btn btn-primary" href="?act=product_sale_rank">销售排行榜</a>
            <a class="btn btn-primary" href="?act=order_detail">商品交易明细</a>
            <a class="btn btn-primary" href="?act=order_detail_summary">商品交易明细汇总</a>
        </div>
        <div class="clear"></div>
    </div>
    <div class="article-main-header">
        <form action="analyse.php" method="get"/>
        <fieldset>
            <p>
            <div class="pull-left">
            </div>
            <div class="pull-right">
                <label>一级分类：</label>
                <select name="top_category" id="top_category" onchange="selectTopCategory">
                    <option value="0">请选择</option>
                </select>

                <label>二级分类：</label>
                <select name="sub_category" id="sub_category">
                    <option value="0">请选择</option>
                </select>

                <label>起始日期：</label>
                <input class="text-input w150" type="text" id="start_date" name="start_date" {literal}onClick="laydate({istime: false, format: 'YYYY-MM-DD', elem: '#start_date'})"{/literal} value="{$start_date}">&nbsp;
                <label>结束日期：</label>
                <input class="text-input w150" type="text" id="end_date" name="end_date" {literal}onClick="laydate({istime: false, format: 'YYYY-MM-DD', elem: '#end_date'})"{/literal} value="{$end_date}">&nbsp;
                <input type="hidden" name="category_id" id="category_id" value="{$category_id}"/>
                <input type="hidden" name="act" value="order_detail"/>
                <button type="submit" class="btn btn-default">汇总</button>
                <button type="submit" name="export" value="export" class="btn btn-default">导出</button>
            </div>
            </p>
        </fieldset>
        </form>
        <div class="clear"></div>
    </div>

    <div class="article-main">
        <table class="table">
            <thead>
            <tr>
                {foreach $header as $head}
                <th>{$head}</th>
                {/foreach}
            </tr>
            </thead>
            <tbody>
            {foreach from=$order_details item=od}
            <tr>
                <td>{$od.product_sn}</td>
                <td>{$od.product_name}</td>
                <td>{$od.category_name}</td>
                <td>{$od.assoc_category_name}</td>
                <td>{$od.product_price}</td>
                <td>{$od.payment_name}</td>
                <td>{$od.pay_status}</td>
                <td>{$od.count}</td>
                <td>{$od.amount}</td>
                <td>{$od.pay_time}</td>
                <td>{$od.add_time}</td>
            </tr>
            {/foreach}
            <tr>
                <td colspan="11">
                    <div class="pull-right">
                        <div class="pages">
                            <span>共有{$total}条，{$totalPage}页</span>
                            {if $go_first}
                            <a href="?page=1&category_id={$category_id}&start_date={$start_date}&end_date={$end_date}&act=order_detail">首页</a>
                            {/if}
                            {if $has_prev}
                            <a href="?page={$page - 1}&category_id={$category_id}&start_date={$start_date}&end_date={$end_date}&act=order_detail">上一页</a>
                            {/if}
                            {if $has_many_prev}
                            ...
                            {/if}
                            {foreach from=$show_page item=pageNum}
                            {if $pageNum eq $page}
                            <b>{$page}</b>
                            {else}
                            <a href="?page={$pageNum}&category_id={$category_id}&start_date={$start_date}&end_date={$end_date}&act=order_detail">{$pageNum}</a>
                            {/if}
                            {/foreach}
                            {if $has_many_next}
                            ...
                            {/if}
                            {if $go_last}
                            <a href="?page={$totalPage}&category_id={$category_id}&start_date={$start_date}&end_date={$end_date}&act=order_detail">末页</a>
                            {/if}
                            {if $has_next}
                            <a href="?page={$page + 1}&category_id={$category_id}&start_date={$start_date}&end_date={$end_date}&act=order_detail">下一页</a>
                            {/if}
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<!-- END content -->
<!-- 日历控件 -->
<script type="text/javascript" src="laydate/laydate.js"></script>
<!-- END 日历控件 -->

<script type="text/javascript">
    var categories = {$categories|json_encode};

    $(function() {
        var category_id = $('#category_id').val();
        var select_top = false;
        var top_categories = [];
        for(var i = 0; i < categories.length; i++) {
            var category = categories[i];
            if(category.parent_id == 0) {
                if(category.id == category_id) {
                    select_top = true;
                }
                var top_category_option = '<option value="' + category.id + '">' + category.name + '</option>';
                top_categories.push(top_category_option);
            }
        }
        $('#top_category').append(top_categories.join("\n"));
        $('#top_category').change(function () {
            selectTopCategory($(this).val());
        });

        if(select_top) {
            selectTopCategory(category_id);
            $('#top_category').val(category_id);
        } else {
            for(var j = 0; j < categories.length; j++) {
                var _category = categories[j];
                if(_category.id == category_id) {
                    selectTopCategory(_category.parent_id);
                    $('#top_category').val(_category.parent_id);
                    $('#sub_category').val(category_id);
                    break;
                }
            }
        }
    });

    function selectTopCategory(id) {
        var top_category_id = id;
        var sub_categories = [
            '<option value="0">请选择</option>'
        ];

        $('#category_id').val(top_category_id);
        $('#sub_category').empty();
        for(var i = 0; i < categories.length; i++) {
            var category = categories[i];

            if(category.parent_id == top_category_id && category.parent_id > 0) {
                var sub_category_option = '<option value="' + category.id + '">' + category.name + '</option>';
                sub_categories.push(sub_category_option);
            }
        }
        $('#sub_category').html(sub_categories.join("\n"));

        $('#sub_category').change(function () {
            selectSubCategory($(this).val());
        });
    }

    function selectSubCategory(id) {
        if(id > 0) {
            $('#category_id').val(id);
        } else {
            $('#category_id').val($('#top_category').val());
        }
    }
</script>

{include file="library/footer.lbi"}
</body>
</html>