{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}

<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">评价管理</h5>
        <div class="clear"></div>
    </div>
    <div class="article-main">
        <div class="article-main-header">
            <div class="clear"></div>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th>用户昵称</th>
                <th>评论内容</th>
                <th>评论时间</th>
                <th>已回复</th>
                <th class="text-right">操作</th>
            </tr>
            </thead>
            <tbody>
            {if $total neq 0}
            {foreach from=$comment_list item=comment}
            <tr>
                <td>{$comment.nickname}</td>
                <td>{$comment.comment}</td>
                <td>{$comment.add_time_str}</td>
                <td>{$comment.responsed}</td>
                <td class="text-right">
                    <a href="?act=comment_show&id={$comment.id}">回复</a>
                    | <a onclick="javascript:if(confirm('确认要删除？')) return true; else return false;" href="?act=comment_delete&id={$comment.id}">删除</a></td>
                </td>
            </tr>
            {/foreach}
            {else}
            <tr>
                <td style="padding: 50px 0" colspan="5" align="center">暂无回复</td>
            </tr>
            {/if}

            <tr>
                <td colspan="5">
                    <div class="pull-right">
                        <div class="pages">
                            <span>共有{$total}条，{$totalPage}页，每页显示：{$count}条</span>
                            {if $go_first}
                            <a href="?page=1&group={$group_str}&order={$order_num}">首页</a>
                            {/if}
                            {if $has_prev}
                            <a href="?page={$page - 1}&group={$group_str}&order={$order_num}">上一页</a>
                            {/if}
                            {if $has_many_prev}
                            ...
                            {/if}
                            {foreach from=$show_page item=pageNum}
                            {if $pageNum eq $page}
                            <b>{$page}</b>
                            {else}
                            <a href="?page={$pageNum}&group={$group_str}&order={$order_num}">{$pageNum}</a>
                            {/if}
                            {/foreach}
                            {if $has_many_next}
                            ...
                            {/if}
                            {if $go_last}
                            <a href="?page={$totalPage}&group={$group_str}&order={$order_num}">末页</a>
                            {/if}
                            {if $has_next}
                            <a href="?page={$page + 1}&group={$group_str}&order={$order_num}">下一页</a>
                            {/if}
                        </div>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<!-- END content -->
{include file="library/footer.lbi"}
</body>
</html>