{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}</h5>
        <div class="pull-right"><a class="btn btn-primary" href="?act=add">添加关键词</a></div>
        <div class="clear"></div>
    </div>
    <div class="ad-main">
        <table class="table">
            <thead>
            <tr>
                <th>关键词</th>
                <th>点击次数</th>
                <th>排序</th>
                <th class="text-right">操作</th>
            </tr>
            </thead>
            <tbody>
            {if $keywords}
            {foreach from=$keywords item=keyword}
            <tr>
                <td>{$keyword.keyword|escape}</td>
                <td>{$keyword.click_count}</td>
                <td>{$keyword.sort}</td>
                <td class="text-right">
                    <a href="?act=edit&id={$keyword.id}">编辑</a> | <a href="javascript:delete_keyword({$keyword.id});">删除</a>
                </td>
            </tr>
            {/foreach}
            {else}
            <tr>
                <td style="padding: 50px 0" colspan="7" align="center">您还没有关键词，立即点击 “<a href="?act=add">这里</a>” 添加关键词！</td>
            </tr>
            {/if}
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
function delete_keyword(id) {
    if(confirm("确定要删除?")) {
        window.location.href = "?act=delete&id="+id;
    }
}
</script>
<!-- END content -->
{include file="library/footer.lbi"}
</body>
</html>
