{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">{$subTitle}-{$exam.title|escape}</h5>
        <div class="pull-right">
            <a class="btn btn-primary" href="exam.php">返回</a>
            <a class="btn btn-primary" href="?act=add&exam_id={$exam.id}">创建问题</a>
        </div>
        <div class="clear"></div>
    </div>
    <div class="ad-main">
        <table class="table">
            <thead>
            <tr>
                <th>编号</th>
                <th>问题</th>
                <th>选项方式</th>
                <th>答案</th>
                <th class="text-right">操作</th>
            </tr>
            </thead>
            <tbody>
            {if $questions}
            {foreach from=$questions item=question name=questions}
            <tr>
                <td>{$smarty.foreach.questions.iteration}</td>
                <td>{$question.title|escape}</td>
                <td>{$question.answer_mode_str}</td>
                <td>{$question.answers}</td>
                <td class="text-right">
                    <a href="?act=edit&exam_id={$exam.id}&id={$question.id}">编辑</a> 
                    | <a href="javascript:delete_question({$question.id});">删除</a></td>
            </tr>
            {/foreach}
            {else}
            <tr>
                <td style="padding: 50px 0" colspan="5" align="center">
                    您问卷还没有创建问题，立即点击 “<a href="?act=add&exam_id={$exam.id}">这里</a>” 创建问题！
                </td>
            </tr>
            {/if}
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
function delete_question(id) {
    if(confirm("确定要删除?")) {
        window.location.href = "?act=delete&id="+id;
    }
}
</script>
<!-- END content -->
{include file="library/footer.lbi"}
</body>
</html>
