<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{$config.site_name|htmlspecialchars}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="{$config.site_name|htmlspecialchars}">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
</head>
<body>
<header class="header" style="position:fixed">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>{$title}</em></h1>
</header>

<!-- 内容开始 -->
<section class="newslist">
    <ul class="newslist-con" id="news-list">
        {if $functions}
        {foreach from=$functions item=function}
        <div class="article-list-item">
            <a href="{$function.url}">
                <img src="{if $function.original}{$function.original|escape}{else}{$template_dir}images/bg_pic.png{/if}"/>
                <p class="clearfix">{$function.name|truncate:8:'...'}</p>
            </a>
        </div>
        {/foreach}
        {/if}
    </ul>
</section>
<div style="height: 2.2rem"></div>
<!-- 底部菜单 -->
<section class="menu">
    <ul>
        <li><a class="active" href="index.php"><em class="icon">&#xe601;</em><span>首页</span></a></li>
        <li><a href="recommend.php"><em class="icon">&#xe626;</em><span>我要分享</span></a></li>
<!--        <li><a href="category.php"><em class="icon">&#xe603;</em><span>分类</span></a></li>-->
        <li><a href="cart.php"><em class="icon">&#xe602;</em><span>购物车</span></a></li>
        <li><a href="user.php"><em class="icon">&#xe604;</em><span>我</span></a></li>
    </ul>
</section>
{include file="dialog.phtml"}
</body>
</html>
