<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{$config.site_name|htmlspecialchars}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="{$config.site_name|htmlspecialchars}">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
</head>
<body>
<header class="header" style="position:fixed">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>商品列表</em></h1>
    <!-- category -->
    <div class="category">
        <dl>
            <dt>
                <a id="shop_category" href="javascript:void(0);">
                    {if $category}
                    {$category.name|escape}
                    {else}
                    分类
                    {/if}
                    <i></i>
                </a>
            </dt>
        </dl>
    </div>
    <!-- 分类菜单-->
    <div class="category_menu">
        <ul class="list1">
            {foreach from=$category_list item=c}
            {if count($c.children) eq 0}
            <li>
                <a href="product_list.php?id={$c.id}">{$c.name}</a>
            </li>
            {else}
            <li class="hasmore">
                <a href="javascript:void(0);" onclick="return false;" grade="2">{$c.name}</a>
                <ul class="list2">
                    {foreach from=$c.children item=cc}
                    <li><a href="product_list.php?id={$cc.id}">{$cc.name}</a></li>
                    {/foreach}
                </ul>
            </li>
            {/if}
            {/foreach}
        </ul>
    </div>
</header>

<!-- 筛选开始 -->
<section class="filter">
    <ul>
        <li class="on" id="index_default">
            <a href="javascript:javascript:sort_products('default');" name="list_sort_index">
                <em>全部</em>
            </a>
        </li>

        <li class="" id="index_sale">
            <a href="javascript:sort_products('sale');" name="list_sort_sales">
                <em>销量</em>
            </a>
        </li>

        <li class="" id="index_star">
            <a href="javascript:sort_products('star');" name="list_sort_score">
                <em>评分</em>
            </a>
        </li>

        <li class="" id="index_price">
            <a href="javascript:sort_products('price');" name="list_sort_price">
                <em>价格</em><!--<span class="arrow_up"></span><span class="arrow_down">  class添加active_up或者active_down </span>-->
            </a>
        </li>

        <!--
        <li class="" id="index_new">
            <a href="javascript:sort_products('new');" name="list_sort_date">
                <em>最新</em>
            </a>
        </li>
        -->
    </ul>
</section>
<!-- 内容开始 -->
<section class="product-list">
    <ul id="product-list">
        {foreach from=$product_list item=product}
        <li>
            <a href="product.php?id={$product.id}">
                <img class="lazy" src="{$template_dir}images/bg_pic.png" data-original="{$product.img}" alt="{$product.name}">
                <dl class="arrow">
                    <dt> {$product.name} </dt>
                    <dd>会员价: ￥{$product.price} <p class="market-price">零售价: <span>¥{$product.shop_price}</span></p> </dd>
                    {if $product.given_integral gt 0}
                    <dd> 赠送: {$product.given_integral|string_format:'%.2f'}积分</dd>
                    {/if}
                </dl>
            </a>
        </li>
        {/foreach}
    </ul>

    <div class="mask" id="mask"></div>
</section>
<div class="cd-popup" role="alert">
    <div class="cd-popup-container" id="message_dialog" style="display: none;">
        <p id="dialog-message"></p>
        <ul class="cd-buttons">
            <li class="cd-signle-button"><a href="javascript:close_message_dialog();">确认</a></li>
        </ul>
        <a href="javascript:close_message_dialog();" class="cd-popup-close img-replace">X</a>
    </div>

    <div class="progressbar">
        <img src="{$template_dir}images/loading.gif"/>
    </div>
</div>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="{$template_dir}js/jquery.lazyload.min.js"></script>
<script type="text/javascript">
    var filter = {$filter};

    function sort_products(mode) {
        var url = "product_list.php";
        var data = { "opera":"sort", "mode":mode, "filter":filter };

        show_mask();
        $("#index_"+mode).siblings().removeClass("on")
        $("#index_"+mode).addClass("on");
        $.post(url, data, sort_products_handler, "json");
    }

    function sort_products_handler(response) {
        hide_mask();
        if(response.error == 0) {
            console.info(response);
            $("#product-list").html(response.content);
            filter = response.filter;
        } else {
            show_message_dialog(response.msg);
        }
    }

    function show_message_dialog(message) {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#dialog-message").text(message);
        $("#message_dialog").show();
    }

    function close_message_dialog() {
        $(".cd-popup").removeClass("is-visible");
        $("#message_dialog").hide();
    }

    function show_mask() {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").show();
    }

    function hide_mask() {
        $(".cd-popup").removeClass("is-visible");
        $(".progressbar").hide();
    }
</script>
<script type="text/javascript">
    $(function() {
        $("img.lazy").lazyload({
            effect : "fadeIn"
        });

        $("#shop_category").click(function(){
            if($(this).hasClass("up")){
                $(".category_menu").slideUp(500);
                $(this).removeClass("up");
                $(".hasmore").removeClass("up");
                $(".hasmore").find("ul").slideUp();
                $('#mask').fadeOut();
            }else{
                $(".category_menu").slideDown(500);
                $(this).addClass("up");
                $('#mask').fadeIn();
            }
        });

        $(".hasmore a").click(function(){
            $(this).parent().siblings().removeClass("up");
            $(this).parent().siblings().find("ul").slideUp(500);
            if($(this).parent().hasClass("up")){
                $(this).parent().find("ul").slideUp(500);
                $(this).parent().removeClass("up");
            }else{
                $(this).parent().find("ul").slideDown(500);
                $(this).parent().addClass("up");
            }
        });
    });
</script>
</body>
</html>
