<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
{foreach from=$product_list name=product_list item=product}
<li>
    <div>
        <a href="product.php?id={$product.id}" name="product_item" title="商品">
            <p class="img">
                <img class="lazy" src="{$product.img}" alt="{$product.name}"/>
            </p >
            <p class="name">{$product.name|truncate:7:'..'}</p >
        </a >
        <p class="price">
            <span class="red">会员价: ¥{$product.price}</span>
            <span class="shop-price">零售价: <i>¥{$product.shop_price}</i></span>
            <span name="item_collect" title="收藏" class="span_sc {if $product.collection}span_sc_on{/if}" id="fav_{$product.product_sn}" onclick="javascript:collection('{$product.product_sn}');" flag="add"></span>
        </p >
        <p class="price">
            {if $product.given_integral gt 0}
            <span class="red">赠送{$product.given_integral|string_format:'%.2f'}积分</span>
            {else}
            <span class="red">&nbsp;</span>
            {/if}
        </p>
    </div>
</li>
{/foreach}