<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{$config.site_name|htmlspecialchars}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="application-name" content="{$config.site_name|htmlspecialchars}">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta name="format-detection" content="telephone=no, address=no">
    <link rel="stylesheet" href="{$template_dir}css/common.css">
    <link rel="stylesheet" href="{$template_dir}css/app.css">
</head>
<body>
<header class="header">
    <a href="javascript:history.back();" class="back"></a>
    <h1><em>确认支付</em></h1>
</header>
<!-- 支付详情 -->
<section class="paycon">
    <div class="paydetail">
        <ul>
            <li>订单编号：{$order.order_sn}</li>
            <li>订单详情：</li>
            {foreach from=$order_detail item=od}
            <li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                {$od.product_name}x{$od.count}
            </li>
            {/foreach}
            <li>支付金额：<i class="red_money">{sprintf("%.2f", $order.amount)}元</i></li>
            <li>支付方式：
                {foreach from=$payment_list item=payment_plugin}
                <span onclick="get_pay_link('{$payment_plugin.plugins}');" {if $payment eq $payment_plugin.plugins}class="on"{/if}>{$payment_plugin.name}</span>
                {/foreach}
            </li>
        </ul>
        <div class="paybtn-con">
            <a href="javascript:topay();" class="paybtn" id="pay_btn">确认支付</a>
        </div>
    </div>
</section>
<div id="mcover" onclick="document.getElementById('mcover').style.display='';" style="display: none;">
    <img src="themes/sbx/images/guide_ios.png">
</div>

<div class="cd-popup" role="alert">
    <div class="cd-popup-container" id="message_dialog" style="display: none;">
        <p id="dialog-message"></p>
        <ul class="cd-buttons">
            <li class="cd-signle-button"><a href="javascript:close_message_dialog();">确认</a></li>
        </ul>
        <a href="javascript:close_message_dialog();" class="cd-popup-close img-replace">X</a>
    </div>

    <div class="progressbar">
        <img src="{$template_dir}images/loading.gif"/>
    </div>
</div>
<script type="text/javascript" src="{$template_dir}js/jquery-1.11.0.min.js"></script>
{if is_weixin()}
<script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.1.0.js"></script>
{/if}
<script type="text/javascript">
    var global_result = null;

    $(function() {
        $(".paydetail ul li span").click(function(){
            $(this).siblings().removeClass("on");
            $(this).addClass("on");
        })
    });

    function topay() {
//        show_message_dialog("等待支付接口申请下来");
    }

    function show_message_dialog(message) {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").hide();
        $("#dialog-message").text(message);
        $("#message_dialog").show();
    }

    function close_message_dialog() {
        $(".cd-popup").removeClass("is-visible");
        $("#message_dialog").hide();
    }

    function get_pay_link(plugins) {
        switch(plugins)
        {
            case "wechat":
                if(window.location.search.search('payment') === -1) {
                    window.history.replaceState(null, null, window.location.href + '&payment=1');
                } else {
                    var target_url = window.location.href;
                    target_url = target_url.substr(0, target_url.search('&payment'));
                    window.history.replaceState(null, null, target_url + '&payment=1');
                }
                get_prepay_id();
                break;
            case "alipay":
                if(is_weixin()) {
                    if(window.location.search.search('payment') === -1) {
                        window.history.replaceState(null, null, window.location.href + '&payment=2');
                    } else {
                        var target_url = window.location.href;
                        target_url = target_url.substr(0, target_url.search('&payment'));
                        window.history.replaceState(null, null, target_url + '&payment=2');
                    }
                    switch(get_device_type()) {
                        case 'iOS':
                            show_ios_guide();
                            break;

                        case 'Android':
                            show_android_guide();
                            break;

                        default:
                            show_message_dialog('请在手机上浏览本页面');
                    }
                } else {
                    ger_pay_link();
                }
                break;
            default:
                show_message_dialog("该支付方式暂无接口支持");
                break;
        }
    }

    function show_ios_guide() {
        document.getElementById('mcover').firstElementChild.src = 'themes/sbx/images/guide_ios.png';
        document.getElementById('mcover').style.display='block';
    }

    function show_android_guide() {
        document.getElementById('mcover').firstElementChild.src = 'themes/sbx/images/guide_android.png';
        document.getElementById('mcover').style.display='block';
    }

    function ger_pay_link() {
        var data = { "opera":"alipay" };
        var url = "topay.php";

        show_mask();
        $.post(url, data, ger_pay_link_handler, "json");
    }

    function ger_pay_link_handler(result) {
        hide_mask();
        if(result.error == 0) {
            $('body').append(result.form);
            document.forms['alipay_submit_form'].submit();
        } else {
            $('#pay_btn').unbind('click');
            show_message_dialog(result.msg);
        }
    }

    function get_prepay_id() {
        var data = { "opera":"wechat" };
        var url = "topay.php";

        show_mask();
        $.post(url, data, get_prepay_id_handler, "json");
    }

    function get_prepay_id_handler(result) {
        hide_mask();
        if(result.error == 0) {
            global_result = result;
            $('#pay_btn').unbind('click');
            $("#pay_btn").bind("click", function() {
                {if is_weixin()}
                //在微信中发起支付
                wx.chooseWXPay({
                    timestamp: global_result.timestamp,
                    nonceStr: global_result.nonce_str,
                    package: 'prepay_id='+global_result.prepay_id,
                    signType: 'MD5',
                    paySign: global_result.sign,
                    success: function (res) {
                        // 支付成功后的回调函数
                        if(res.errMsg == "chooseWXPay:ok") {
                            window.location.href = "payresult.php";
                        } else {
                            show_message_dialog(res.errMsg+":支付失败");
                        }
                    }
                });
                {else}
                //在浏览器中发起支付
                window.location.href = global_result.mweb_url;
                {/if}
            });
        } else {
            $('#pay_btn').unbind('click');
            show_message_dialog(result.msg);
        }
    }

    function show_mask() {
        $(".cd-popup").addClass("is-visible");
        $(".progressbar").show();
    }

    function hide_mask() {
        $(".cd-popup").removeClass("is-visible");
        $(".progressbar").hide();
    }

    function get_device_type() {
        if (/(Android)/i.test(navigator.userAgent)) {
            return 'Android';
        } else if (/(iPhone|iPad|iPod|iOS)/i.test(navigator.userAgent)) {
            return 'iOS';
        }

        return 'pc';
    }

    function is_weixin(){
        var ua = window.navigator.userAgent.toLowerCase();
        //通过正则表达式匹配ua中是否含有MicroMessenger字符串
        if(ua.match(/MicroMessenger/i) == 'micromessenger'){
            return true;
        }else{
            return false;
        }
    }

    {if is_weixin()}
    wx.config({
        appId: '{$signPackage.appId}',
        timestamp: {$signPackage.timestamp},
        nonceStr: '{$signPackage.nonceStr}',
        signature: '{$signPackage.signature}',
        jsApiList: [
            'chooseWXPay',
            'closeWindow'
        ]
    });
    {/if}
</script>
{if $payment eq 'alipay'}
{$payment_exec}
<script type="text/javascript">
    $(function () {
        $('#pay_btn').unbind('click');
        $('#pay_btn').click(function () {
            document.forms['alipay_submit_form'].submit();
        });
    });
</script>
{else}
<script type="text/javascript">
    $(function () {
        $('#pay_btn').unbind('click');
        $('#pay_btn').click(function () {
            {if isset($payment_exec.mweb_url)}
            window.location.href = '{$payment_exec.mweb_url}';
            {else}
            wx.chooseWXPay({
                timestamp: {$payment_exec.timestamp},
                nonceStr: '{$payment_exec.nonce_str}',
                package: 'prepay_id={$payment_exec.prepay_id}',
                signType: 'MD5',
                paySign: '{$payment_exec.sign}',
                success: function (res) {
                    // 支付成功后的回调函数
                    if(res.errMsg == "chooseWXPay:ok") {
                        window.location.href = "payresult.php";
                    } else {
                        show_message_dialog(res.errMsg+":支付失败");
                    }
                }
            });
            {/if}
        });
    });
</script>
{/if}
</body>
</html>
