{include file="library/header.lbi"}
<body>
{include file="library/navbar.lbi"}
{include file="library/sidebar.lbi"}
<style>
{literal}
    .select-image {
        cursor: pointer;
    }
{/literal}
</style>

<script src="js/jquery.modal.min.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="css/jquery.modal.css" type="text/css" media="screen" />
<!-- content -->
<div id="content">
    <div class="content-title">
        <h5 class="pull-left">修改销量</h5>
        <div class="clear"></div>
    </div>
    <div class="adminUser-main">
        <form id="productAddForm" name="productAddForm" method="post">
            <fieldset>
                <p>
                    <label class="l-title">产品：</label>
                    <span class="text-input w300">{$product.name|escape}</span>
                </p>
                <p>
                    <label class="l-title">当前销量：</label>
                    <span class="text-input w300">{$product.sale_count}</span>
                </p>
                <p>
                    <label class="l-title">销量：</label>
                    <input class="text-input w300" type="number" name="sale_count" value="{$product.sale_count}" placeholder="请填写销量"/>
                </p>
                <p>
                    <label class="l-title"></label>
                    <input type="hidden" name="opera" value="sale_count" />
                    <input type="hidden" name="product_sn" value="{$product.product_sn}" />
                    <button class="btn btn-primary" type="button" onclick="do_submit();">修改</button> &nbsp;
                </p>
            </fieldset>
        </form>
    </div>
</div>

<!-- END content -->
<script type="text/javascript">
$(function() {
});

function do_submit() {
    document.getElementById('productAddForm').submit();
}
</script>
{include file="library/footer.lbi"}
</body>
</html>